name: parkware
description: Parkware.
publish_to: "none"
version: 0.1.0

environment:
  sdk: ">=3.0.5 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  google_fonts: ^6.1.0
  iconly: ^1.0.1
  firebase_core: ^2.17.0
  firebase_auth: ^4.10.1
  google_sign_in: ^6.1.5
  go_router: ^13.2.0
  http: ^1.2.0
  google_maps_flutter: ^2.0.8
  location: ^4.3.0
  fluttertoast: ^8.2.4
  barcode_scanner: ^3.6.2
  flutter_stripe: ^10.1.1
  flutter_ticket_view: ^1.0.0
  flutter_dotenv: ^5.0.2
  provider: ^5.0.0
  restart_app: ^1.2.1
  qr_flutter: ^4.1.0
  flutter_barcode_scanner: ^2.0.0
  socket_io_client: ^2.0.3+1
  web_socket_channel: ^2.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  test: ^1.24.9
  flutter_launcher_icons: ^0.13.1

flutter:
  uses-material-design: true

  assets:
    - assets/
    - .env

flutter_icons:
  android: true
  ios: true
  image_path: "assets/AppIcons/appstore.png"